INSERT INTO positions (name)
VALUES ('admin'),
       ('moderator'),
       ('user');

-- Добавяне на потребители
INSERT INTO users (first_name, last_name, username, password, email, profile_photo, position_id, is_blocked)
VALUES ('John', 'Smith', 'johndoe', 'password123', 'john.doe@example.com', '/assets/img/bitAvatar1.png', 1, FALSE),
       ('Jane', 'Smith', 'janesmith', 'password123', 'jane.smith@example.com', '/assets/img/bitAvatar1.png', 1, FALSE),
       ('Alice', 'Johnson', 'alicejohnson', 'password123', 'alice.johnson@example.com', '/assets/img/bitAvatar1.png', 2,
        FALSE),
       ('Bobby', 'Williams', 'bobwilliams', 'password123', 'bob.williams@example.com', '/assets/img/bitAvatar1.png', 3,
        FALSE),
       ('Charlie', 'Brown', 'charliebrown', 'password123', 'charlie.brown@example.com', '/assets/img/bitAvatar1.png', 3,
        FALSE),
       ('David', 'Wilson', 'davidwilson', 'password123', 'david.wilson@example.com', '/assets/img/bitAvatar1.png', 3,
        FALSE),
       ('Eveline', 'Davis', 'evadavis', 'password123', 'eva.davis@example.com', '/assets/img/bitAvatar1.png', 3, FALSE),
       ('Frank', 'Miller', 'frankmiller', 'password123', 'frank.miller@example.com', '/assets/img/bitAvatar1.png', 3,
        FALSE),
       ('Grace', 'Taylor', 'gracetaylor', 'password123', 'grace.taylor@example.com', '/assets/img/bitAvatar1.png', 3,
        FALSE),
       ('Hank', 'Moore', 'hankmoore', 'password123', 'hank.moore@example.com', '/assets/img/bitAvatar1.png', 3, FALSE),
       ('Ivet', 'Anderson', 'ivyanderson', 'password123', 'ivy.anderson@example.com', '/assets/img/bitAvatar1.png', 3,
        FALSE),
       ('Jack', 'Thomas', 'jackthomas', 'password123', 'jack.thomas@example.com', '/assets/img/bitAvatar1.png', 3,
        FALSE),
       ('Kathy', 'Jackson', 'kathyjackson', 'password123', 'kathy.jackson@example.com', '/assets/img/bitAvatar1.png', 3,
        FALSE),
       ('Leonardo', 'White', 'leowhite', 'password123', 'leo.white@example.com', '/assets/img/bitAvatar1.png', 3,
        FALSE),
       ('Mila', 'Harris', 'miaharris', 'password123', 'mia.harris@example.com', '/assets/img/bitAvatar1.png', 3, FALSE),
       ('Nate', 'Martin', 'natemartin', 'password123', 'nate.martin@example.com', '/assets/img/bitAvatar1.png', 3,
        FALSE),
       ('Olivia', 'Garcia', 'oliviagarcia', 'password123', 'olivia.garcia@example.com', '/assets/img/bitAvatar1.png', 3,
        FALSE),
       ('Paul', 'Rodriguez', 'paulrodriguez', 'password123', 'paul.rodriguez@example.com', '/assets/img/bitAvatar1.png',
        3, FALSE),
       ('Quinn', 'Lewis', 'quinnlewis', 'password123', 'quinn.lewis@example.com', '/assets/img/bitAvatar1.png', 3,
        FALSE),
       ('Rita', 'Walker', 'ritawalker', 'password123', 'rita.walker@example.com', '/assets/img/bitAvatar1.png', 3,
        FALSE);

-- Добавяне на телефонни номера за администратори
INSERT INTO admin_phones (phone_number, user_id)
VALUES ('+1234567890', 1),
       ('+0987654321', 1),
       ('+1122334455', 2);

-- Добавяне на постове
INSERT INTO posts (user_id, title, content, likes, dislikes)
VALUES (1, 'The Future of Crypto Trading',
        'In this post, we will discuss the future trends in crypto trading and how to prepare for them. Get ready to learn about the upcoming technologies and strategies that will shape the market.',
        5, 1),
       (2, 'How to Analyze Crypto Markets',
        'This post covers the fundamental techniques for analyzing cryptocurrency markets, including technical analysis, fundamental analysis, and the importance of market sentiment.',
        3, 0),
       (3, 'Best Practices for Secure Crypto Trading',
        'Learn the best practices for keeping your crypto investments safe from scams, hacks, and other threats. This post includes tips on using secure wallets and avoiding common pitfalls.',
        7, 2),
       (4, 'Top 5 Cryptocurrencies to Watch in 2024',
        'Explore the top five cryptocurrencies that are expected to perform well in 2024. This post provides insights into each cryptocurrency and why it is worth keeping an eye on.',
        8, 3),
       (5, 'Understanding Crypto Trading Bots',
        'Crypto trading bots can help automate your trading strategy. This post explains how these bots work, their benefits, and some popular options available in the market.',
        2, 1),
       (1, 'Crypto Trading Myths Debunked',
        'This post clears up some of the most common myths about crypto trading.',
        4, 0),
       (2, 'Introduction to Decentralized Finance (DeFi)',
        'An overview of DeFi, how it works, and why it’s the next big thing in crypto.',
        6, 2),
       (3, 'The Role of AI in Crypto Trading',
        'Exploring how artificial intelligence is changing the landscape of crypto trading.',
        10, 1),
       (4, 'How to Choose a Reliable Crypto Exchange',
        'Tips and tricks for selecting a trustworthy platform for trading cryptocurrencies.',
        3, 1),
       (5, 'The Impact of Regulations on Crypto Markets',
        'Analyzing how different regulations affect the global crypto markets.',
        5, 0),
       (6, 'Crypto Trading Strategies for Beginners',
        'A guide to some simple but effective trading strategies for those new to crypto.',
        8, 3),
       (7, 'Understanding Blockchain Technology',
        'An in-depth look at how blockchain technology works and its applications.',
        9, 1),
       (8, 'The Future of NFTs',
        'Discussing the potential future developments and applications of NFTs.',
        7, 2),
       (9, 'Crypto Market Volatility Explained',
        'Why crypto markets are so volatile and how to manage risk.',
        4, 0),
       (10, 'Staking vs. Mining: What’s the Difference?',
        'A comparison of two popular methods for earning crypto rewards.',
        2, 1),
       (11, 'How to Secure Your Crypto Wallet',
        'Best practices for ensuring the safety of your cryptocurrency holdings.',
        3, 1),
       (12, 'The Environmental Impact of Cryptocurrency Mining',
        'Analyzing the ecological consequences of crypto mining and how it can be mitigated.',
        1, 2),
       (13, 'Top Crypto News Sources to Follow',
        'A list of the best sources for staying updated on cryptocurrency news.',
        6, 0),
       (14, 'Understanding Crypto Taxation',
        'A guide to the basics of cryptocurrency taxation and compliance.',
        5, 1),
       (15, 'The Rise of Stablecoins',
        'Exploring why stablecoins are becoming an important part of the crypto ecosystem.',
        8, 2),
       (16, 'How to Avoid Crypto Scams',
        'Tips for identifying and avoiding common cryptocurrency scams.',
        10, 1),
       (17, 'The History of Bitcoin',
        'A look at the origins and evolution of Bitcoin since its inception.',
        12, 4),
       (18, 'The Benefits of Crypto Diversification',
        'Why diversifying your crypto portfolio is essential for long-term success.',
        9, 1),
       (19, 'Understanding Market Sentiment in Crypto',
        'How to read and interpret market sentiment to make better trading decisions.',
        7, 2),
       (20, 'The Future of Cross-Chain Technology',
        'How cross-chain solutions could revolutionize the crypto industry.',
        4, 1),
       (1, 'A Beginner’s Guide to Yield Farming',
        'An introduction to yield farming and how to start earning passive income with crypto.',
        11, 3),
       (2, 'What are Privacy Coins?',
        'Exploring the top privacy coins and their importance in the crypto world.',
        8, 1),
       (3, 'The Evolution of Crypto Exchanges',
        'How crypto exchanges have evolved over the years and what to expect next.',
        5, 0),
       (4, 'Crypto Trading Psychology',
        'Understanding the role of psychology in trading and how to manage your emotions.',
        3, 2),
       (5, 'The Importance of Liquidity in Crypto Markets',
        'Why liquidity is crucial and how it affects your trading experience.',
        7, 1),
       (6, 'Exploring the Metaverse',
        'How the Metaverse is integrating with cryptocurrency and blockchain technology.',
        9, 1),
       (8, 'How to Create Your Own Cryptocurrency',
        'A step-by-step guide to launching your own cryptocurrency.',
        6, 1),
       (9, 'The Role of Oracles in Blockchain',
        'Understanding how oracles bring real-world data to blockchain networks.',
        8, 2),
       (10, 'The Ethics of Crypto Trading',
        'A discussion on the ethical considerations in the world of cryptocurrency.',
        5, 1),
       (11, 'Top 10 Crypto Wallets for 2024',
        'A review of the best crypto wallets available in 2024.',
        7, 3),
       (12, 'What is a Hard Fork?',
        'Explaining the concept of hard forks and their impact on the blockchain.',
        2, 0),
       (13, 'The Importance of Decentralization',
        'Why decentralization is a key principle in the world of crypto.',
        6, 2),
       (14, 'Understanding Gas Fees',
        'A detailed guide to gas fees and how to minimize them when trading crypto.',
        10, 1),
       (15, 'The Future of Central Bank Digital Currencies (CBDCs)',
        'Exploring the potential of CBDCs and their implications for the global financial system.',
        3, 2);

-- Добавяне на коментари
INSERT INTO comments (post_id, user_id, content)
VALUES
    (1, 3, 'Great insights! I’m particularly interested in the section about upcoming technologies.'),
    (1, 4, 'I agree, the future looks promising. Thanks for sharing this post.'),
    (2, 5, 'Can you provide more details on technical analysis? It would be helpful.'),
    (2, 6, 'Yes, a deeper dive into technical analysis would be great.'),
    (3, 7, 'Security is crucial in crypto trading. Thanks for highlighting these practices.'),
    (3, 8, 'I found this post very informative. Always good to be aware of potential threats.'),
    (4, 9, 'Interesting list! I’m excited to see how these cryptocurrencies perform.'),
    (4, 10, 'I’m curious about the criteria you used to select these top five cryptocurrencies.'),
    (5, 11, 'Trading bots seem like a good idea. How do I choose the right one?'),
    (5, 12, 'I’m new to trading bots. Any recommendations for beginners?'),
    (6, 13, 'This is very helpful for beginners. Thanks for sharing!'),
    (6, 14, 'I’ve just started trading, and these strategies are really useful.'),
    (7, 15, 'Blockchain technology is fascinating. Great explanation!'),
    (7, 16, 'I never fully understood blockchain until now. Thanks!'),
    (8, 17, 'The potential of NFTs is huge. Can’t wait to see what’s next.'),
    (8, 18, 'I’m still trying to wrap my head around NFTs. This post helped.'),
    (9, 19, 'Volatility is indeed a challenge. Good tips on managing it.'),
    (9, 20, 'Market volatility is what makes crypto so exciting.'),
    (10, 1, 'I wasn’t aware of the differences between staking and mining. Interesting!'),
    (10, 2, 'This post clarified a lot for me. Thanks for the comparison.'),
    (11, 3, 'Security should always be a top priority. Good advice.'),
    (11, 4, 'Can you suggest some secure wallets for beginners?'),
    (12, 5, 'I didn’t realize how much energy mining consumes. Eye-opening!'),
    (12, 6, 'It’s concerning to see the environmental impact of mining.'),
    (13, 7, 'Staying informed is key in the crypto world. Thanks for the list.'),
    (13, 8, 'These news sources are really reliable. I follow most of them.'),
    (14, 9, 'Crypto taxation can be tricky. Appreciate the guide.'),
    (14, 10, 'It’s good to know the basics of crypto taxation.'),
    (15, 11, 'Stablecoins are becoming essential. Good overview.'),
    (15, 12, 'I’ve been curious about stablecoins. This post was informative.'),
    (16, 13, 'Scams are everywhere. Thanks for the tips on staying safe.'),
    (16, 14, 'It’s scary how sophisticated some scams are.'),
    (17, 15, 'Bitcoin’s history is so interesting. Great read!'),
    (17, 16, 'It’s amazing how far Bitcoin has come since its inception.'),
    (18, 17, 'Diversification is key in any investment. Solid advice.'),
    (18, 18, 'This post reinforces the importance of a balanced portfolio.'),
    (19, 19, 'Understanding market sentiment is crucial. Well explained.'),
    (19, 20, 'Market sentiment often drives price action.'),
    (20, 1, 'Cross-chain technology could be a game-changer.'),
    (20, 2, 'I’m excited to see how cross-chain solutions develop.'),
    (21, 3, 'Yield farming sounds complex, but this guide simplifies it.'),
    (21, 4, 'Thanks for breaking down yield farming for beginners.'),
    (22, 5, 'Privacy coins are intriguing. Thanks for the overview.'),
    (22, 6, 'I’ve been hearing a lot about privacy coins. This was helpful.');


-- Добавяне на тагове
INSERT INTO tags (name)
VALUES ('Crypto Trading'),
       ('Market Analysis'),
       ('Security'),
       ('Investment Strategies'),
       ('Trading Bots');

-- Свързване на постове с тагове
INSERT INTO post_tags (post_id, tag_id)
VALUES (1, 1),
       (1, 2),
       (2, 2),
       (3, 3),
       (4, 1),
       (4, 4),
       (5, 5);

-- Добавяне на реакции на постове
INSERT INTO posts_users_likes (post_id, user_id)
VALUES (1, 3),
       (1, 4),
       (2, 5),
       (3, 7),
       (3, 8),
       (4, 9),
       (4, 10),
       (5, 11),
       (5, 12);
